build-test:
  stage: deploy
  script:
    - mvn clean package -DskipTests -Dspring.config.location=/opt/esup-agape-test/application-test.properties
    - ssh -tt -o StrictHostKeyChecking=no gitlab-runner@aibes sudo systemctl stop esup-agape-test.service
    - rm -f /opt/esup-agape-test/esup-agape.war
    - cp target/esup-agape.war /opt/esup-agape-test/
    - ssh -tt -o StrictHostKeyChecking=no gitlab-runner@aibes sudo systemctl restart esup-agape-test.service
  only:
    - test
  tags:
    - test

build-prod:
  stage: deploy
  script:
    - mvn clean package -DskipTests -Dspring.config.location=/opt/esup-agape/application.properties
    - ssh -tt -o StrictHostKeyChecking=no gitlab-runner@aibes sudo systemctl stop esup-agape.service
    - rm -f /opt/esup-agape/esup-agape.war
    - cp target/esup-agape.war /opt/esup-agape/
    - ssh -tt -o StrictHostKeyChecking=no gitlab-runner@aibes sudo systemctl restart esup-agape.service
  only:
    - tags
  except:
    - dev
    - test
    - main
  tags:
    - prod
