package org.esupportail.esupagape.entity.enums;

public enum Classification {

    AUTISME,
    AUTRES_TROUBLES,
    TROUBLES_DES_FONCTIONS_VISUELLES,
    DEFICIENCE_AUDTIVE_AUTRE,
    DEFICIENCE_VISUELLE_AUTRE,
    MOTEUR,
    NON_COMMUNIQUE,
    REFUS,
    SURDITE_SEVERE_ET_PROFONDE,
    TEMPORAIRE,
    TROUBLE_DU_LANGAGE_OU_DE_LA_PAROLE,
    TROUBLES_INTELLECTUELS_ET_COGNITIFS,
    TROUBLES_PSYCHIQUES,
    TROUBLES_VISCERAUX,
    TROUBLES_VISCERAUX_CANCER

}
